name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Stats Card
        uses: anuraghazra/github-readme-stats@master
        env:
          INCLUDE_ALL_COMMITS: true
        with:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Ankur2606
          HIDE_BORDER: true
          THEME: transparent
          TITLE_COLOR: 3b82f6
          TEXT_COLOR: 94a3b8
          ICON_COLOR: a78bfa
          OUTPUT: public/github-stats.svg # Saves to your public folder
          
      - name: Generate Top Languages Card
        uses: anuraghazra/github-readme-stats@master
        with:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Ankur2606
          HIDE_BORDER: true
          THEME: transparent
          TITLE_COLOR: 3b82f6
          TEXT_COLOR: 94a3b8
          LAYOUT: compact
          CARD_TYPE: top-langs
          OUTPUT: public/github-langs.svg

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add public/github-stats.svg public/github-langs.svg
          git commit -m "chore: update github stats" || echo "No changes to commit"
          git push
